### ISSUE TITLE
Invalid zip

### ISSUE THREAD

**Issue by ebkr** [LeagueRaINi/RoR2-Artifacts#2]
Hi, downloading the zip through both Thunderstore manually, and managers causes errors as the archive can't be extracted properly.

Extracting from windows's archive manager produces the following error: 
![image](https://user-images.githubusercontent.com/10426228/76701744-c5b34880-66bb-11ea-9b92-e7c0939d1368.png)

Running the following command:

`Expand-Archive -LiteralPath ./1.0.0.zip -DestinationPath ./1.0.0`

produces:
![image](https://user-images.githubusercontent.com/10426228/76701761-f2676000-66bb-11ea-9ffd-fc62cc3ab6ff.png)

and zlib, used by both r2modman and RoR2MM throws the following error:

![image](https://user-images.githubusercontent.com/10426228/76701771-07dc8a00-66bc-11ea-80eb-729854ff3e4b.png)

**Comment by LeagueRaINi** [comment]
guess i will try to repack it, already wrote about this with mythic but we thought its only an issue with the mod manager since manually unpacking it works fine for both of us

**Comment by LeagueRaINi** [comment]
should be fixed now, seems like i packed it with lzma which zlib doesnt support

**Comment by ebkr** [comment]
Seems to be fine, thanks
